# Generated by Django 3.1.3 on 2020-11-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cambiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraseña', models.TextField(max_length=30)),
                ('contraseña2', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Crear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(max_length=30)),
                ('nombre', models.TextField(max_length=30)),
                ('contraseña', models.TextField(max_length=30)),
                ('contraseña2', models.TextField(max_length=30)),
                ('correo', models.TextField(max_length=30)),
                ('telefono', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Ingresar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(max_length=30)),
                ('contraseña', models.TextField(max_length=30)),
            ],
        ),
    ]
